### ISSUE TITLE
Floating labels for Password inputs not triggering on Chrome auto-fill

### ISSUE THREAD

**Issue by AmmarHasan** [mseemann/angular2-mdl#1169]
When using the following input code, floating labels aren't triggering on auto-fill for the Password inputs (they're working fine for text inputs) : 
```
<div class="login__form">
  <div>
    <mdl-textfield floating-label [(ngModel)]="username" [label]="'Username'" name="__ac_name"></mdl-textfield>
  </div>
  <div>
    <mdl-textfield floating-label [(ngModel)]="password" [label]="'Password'" type="password" name="__ac_password"></mdl-textfield>
  </div>
</div>
```

Screenshot: 
![screen shot 2017-08-25 at 2 15 21 pm](https://user-images.githubusercontent.com/5666662/29709708-db760864-89a6-11e7-960b-9f72e2a3fc7f.png)

**Comment by mseemann** [comment]
they discussed it here: https://github.com/google/material-design-lite/issues/1253

**Comment by zucker-rdrg** [comment]
This workaround works for me:
```css
input:-webkit-autofill ~ .mdl-textfield__label {
  top: $input-text-vertical-spacing - ($input-text-floating-label-fontsize + $input-text-padding);
  color: $input-text-highlight-color;
  font-size: $input-text-floating-label-fontsize;
}
```
