### ISSUE TITLE
Dialog width

### ISSUE THREAD

**Issue by BrentDietrich** [mseemann/angular2-mdl#148]
Is there a simple way to adjust dialog widths on a per dialog basis? Right now, we're adjusting a custom dialog using the following method...

`changeWidth() {

    setTimeout(() => {
      let dialogEls = document.getElementsByClassName('mdl-dialog');
      let elements = Array.prototype.filter.call(dialogEls, (dialogEl) => {
        if (dialogEl.nodeName === 'MDL-DIALOG-HOST-COMPONENT') {
          let hostComp = dialogEl.lastChild;
          if ((hostComp || {}).nodeName === 'CUSTOM-DIALOG-CMP') {
            return true;
          }
        }
      })
      elements.forEach(el => {
        el.style.width = '500px';
      });
    });

  }`

We're looking for a cleaner option. Any help would be greatly appreciated.

**Comment by mseemann** [comment]
right now there is not. The dialog width is a preset from material-design-lite. from the sources:

```scss
/* Dialog */

@mixin dialog-width($units:5) {
  @if(type_of($units) != 'number') {
    @error "The unit given to dialog-width should be a number.";
  }
  // 56dp is the base unit width for Dialogs.
  // With 5 units being the number of units for a mobile device.
  // https://material.google.com/components/dialogs.html#dialogs-simple-dialogs
  width: $units * 56px;
}
```

your case looks like you want to change the width for all dialogs. you can do this with css if this is done after the mdl-css is loaded
```css
.mdl-dialog {
   width: 500px;
}
```
